version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/backend/data/postgres
    ports:
      - "5431:5432"


  api:
    container_name: api
    build: 
      context: backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_NAME}
    ports:
        - 3333:3333
    command: python3 src/app.py
    depends_on:
        - "postgres"
    restart: always



  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      REACT_APP_CURRENT_IP: ${REACT_APP_CURRENT_IP}
      CHOKIDAR_USEPOLLING: true
      
    depends_on:
    - "api"
volumes:
    postgres: