version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/backend/data/postgres
    ports:
      - "5431:5432"


  api:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
        - 3333:3333
    
    command: python3 src/app.py
    depends_on:
        - "postgres"
volumes:
    postgres: